name: Test package publishing

on: [push]

jobs:
  publish:
    name: Publish package
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}
        run: .\tcli.exe publish
